# Generated by Django 3.2.7 on 2021-09-22 09:28

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=30)),
                ('appimage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('author', models.CharField(max_length=30)),
                ('livelink', models.URLField(null=True)),
                ('design', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('usability', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('content', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userPhoto', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('bio', models.TextField()),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
