# Generated by Django 3.2.7 on 2021-09-22 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreview', '0003_auto_20210922_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appvote',
            name='content',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(1)]),
        ),
    ]
