# Generated by Django 3.2.7 on 2021-09-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appreview', '0003_alter_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='firstname',
        ),
    ]
