# Generated by Django 3.2.7 on 2021-09-23 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreview', '0005_alter_appvote_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appvote',
            name='content',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MaxValueValidator(9.9), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='appvote',
            name='design',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MaxValueValidator(9.9), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='appvote',
            name='total',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='appvote',
            name='usability',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MaxValueValidator(9.9), django.core.validators.MinValueValidator(1)]),
        ),
    ]
